services:
  db:
    image: postgres:16-alpine
    container_name: loki_db
    environment:
      POSTGRES_DB: ${LOKI_DB}
      POSTGRES_USER: ${LOKI_USER}
      POSTGRES_PASSWORD: ${LOKI_PASSWORD}
    ports:
      - '${LOKI_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
